# Configuration matching NeuralDecoder's TensorFlow implementation
# Based on: NeuralDecoder/neuralDecoder/configs/model/gru_stack_inputNet.yaml

# Runtime configuration
gpu_number: '0'
mode: train
use_amp: true

# Output paths
output_dir: /opt/ml/output
checkpoint_dir: /opt/ml/model/checkpoint
init_from_checkpoint: false
init_checkpoint_path: None

# Checkpointing
save_best_checkpoint: true
save_all_val_steps: false
save_final_model: false
save_val_metrics: true

# Logging
batches_per_train_log: 10
batches_per_val_step: 500
batches_per_save: 0
log_individual_day_val_PER: true
log_val_skip_logs: false
save_val_logits: true
save_val_data: false

model:
  # Use the NeuralDecoder architecture
  use_neural_decoder_model: true
  
  # Input features
  n_input_features: 512
  #neural_dim: 512
  
  # GRU configuration (matching NeuralDecoder)
  n_units: 512  # Hidden units per GRU layer (was 1024 in original)
  n_layers: 5
  bidirectional: false
  
  # Dropout
  rnn_dropout: 0.4  # GRU dropout (matching NeuralDecoder)
  rnn_trainable: true  # Make GRU layers trainable
  
  # Weight regularization
  weight_reg: 0.00001  # L2 regularization (1e-5)
  
  # Patching/Stacking configuration (matching NeuralDecoder)
  patch_size: 14  # kernel_size in TF version
  patch_stride: 4  # strides in TF version
  
  # Input network (day-specific layers)
  input_network:
    n_input_layers: 1
    input_layer_sizes: [256]  # 512 -> 256 projection
    input_trainable: true
    input_layer_dropout: 0.2
    activation: 'softsign'
  
  # Initial hidden state
  h0: 'learned'  # Use learned initial states
  
  # Subsampling (not used by default)
  subsample_factor: 1
  
  # Output size (calculated automatically)
  output_size: 512  # n_units * (2 if bidirectional else 1)

# Training configuration
# Optimizer
optimizer: 'adam'
beta0: 0.9
beta1: 0.999
epsilon: 1.0e-8
weight_decay: 0.00001  # L2 regularization via optimizer
weight_decay_day: 0
seed: 42

# Learning rate schedule (matching NeuralDecoder linear decay)
lr_scheduler_type: linear
lr_max: 0.02  # Initial learning rate
lr_min: 0.0005  # Final learning rate  
lr_warmup_steps: 1000
lr_decay_steps: 94000  # Total training steps

# Day-specific learning rates
lr_max_day: 0.02
lr_min_day: 0.0005
lr_decay_steps_day: 94000
lr_warmup_steps_day: 1000

# Gradient clipping
grad_norm_clip_value: 10.0

# Training steps
num_training_batches: 94000  # ~120 epochs for your dataset

# Early stopping
early_stopping: true
early_stopping_val_steps: 20

# Composite loss configuration
use_composite_loss: true  # Enable both diphone and phoneme CTC losses
composite_loss_alpha: 0.6  # Static alpha (ignored if use_alpha_schedule=true)
use_alpha_schedule: true  # Enable dynamic curriculum learning
alpha_schedule_start: 0.0  # Start with diphone-only (0% phoneme)
alpha_schedule_end: 0.6  # End with 60% phoneme, 40% diphone
alpha_schedule_step_size: 0.1  # Increase alpha by 0.1
alpha_schedule_step_interval: 3000  # Every 3000 batches (as requested)

# Dataset configuration
dataset:
  # Data transforms (augmentation)
  data_transforms:
    white_noise_std: 1.0
    constant_offset_std: 0.2
    random_walk_std: 0.0
    random_walk_axis: -1
    static_gain_std: 0.0
    random_cut: 3
    smooth_kernel_size: 100
    smooth_data: true
    smooth_kernel_std: 2
  
  neural_dim: 512
  batch_size: 32 # Further reduced for stability (was 48)
  n_classes: 1681 # DIPHONES (was 41 phonemes)
  max_seq_elements: 500
  days_per_batch: 4
  seed: 1
  num_dataloader_workers: 4 # parallel S3 reads (reduce to 2 if issues)
  loader_shuffle: false
  must_include_days: null
  test_percentage: 0.1
  feature_subset: null

  # This will be overridden to use S3 paths
  dataset_dir: /dummy
  bad_trials_dict: null
  
  # Sessions (days) - all 48 sessions
  sessions:
  - t15.2023.08.11
  - t15.2023.08.13
  - t15.2023.08.18
  - t15.2023.08.20
  - t15.2023.08.25
  - t15.2023.08.27
  - t15.2023.09.01
  - t15.2023.09.03
  - t15.2023.09.24
  - t15.2023.09.29
  - t15.2023.10.01
  - t15.2023.10.06
  - t15.2023.10.08
  - t15.2023.10.13
  - t15.2023.10.15
  - t15.2023.10.20
  - t15.2023.10.22
  - t15.2023.11.03
  - t15.2023.11.04
  - t15.2023.11.17
  - t15.2023.11.19
  - t15.2023.11.26
  - t15.2023.12.03
  - t15.2023.12.08
  - t15.2023.12.10
  - t15.2023.12.17
  - t15.2023.12.29
  - t15.2024.02.25
  - t15.2024.03.03
  - t15.2024.03.08
  - t15.2024.03.15
  - t15.2024.03.17
  - t15.2024.04.25
  - t15.2024.04.28
  - t15.2024.05.10
  - t15.2024.06.14
  - t15.2024.07.19
  - t15.2024.07.21
  - t15.2024.07.28
  - t15.2025.01.10
  - t15.2025.01.12
  - t15.2025.03.14
  - t15.2025.03.16
  - t15.2025.03.30
  - t15.2025.04.13
  
  dataset_probability_val:
  - 0 # no val or test data from this day
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0 # no val or test data from this day
  - 1
  - 1
  - 1
  - 0 # no val or test data from this day
  - 0 # no val or test data from this day
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  
  nInputFeatures: 512
  
  # Gaussian smoothing
  gaussian_smoothing_sigma: 0
  
  # Data augmentation
  use_gaussian_smoothing: false
  gaussian_smoothing_sigma_range: [0, 2.0]
  use_random_time_warp: false
  time_warp_factor_range: [0.95, 1.05]
